<a href="https://colab.research.google.com/github/rrohan1920/mk-labs-file/blob/main/numpypandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
print(np.__version__ , pd.__version__)

1.26.4 2.2.2


In [ ]:
arr = np.array([1, 2, 3, 4, 5])
arr

array([1, 2, 3, 4, 5])

In [ ]:
zeros_arr = np.zeros((3, 3))  # 3x3 array of zeros
zeros_arr

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
identity = np.eye(4)  # 4x4 identity matrix
identity


array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
random_arr = np.random.random((2, 2))  # 2x2 array of random floats
random_arr

array([[0.90671064, 0.04699798],
       [0.58288998, 0.03660869]])

In [ ]:
reshaped = np.reshape(arr, (5, 1))  # Reshape to 5x1


In [ ]:
sliced_arr = arr[1:4]  # Get elements from index 1 to 3


In [ ]:
sliced_arr = arr[1:4]  # Get elements from index 1 to 3


In [ ]:
result = arr + 2  # Adds 2 to every element in arr


In [ ]:
result = arr * 2  # Multiplies every element in arr by 2


In [ ]:
result = np.dot(arr, arr)  # Dot product of arr with itself


In [ ]:
max_value = np.max(arr)


In [ ]:
total = np.sum(arr)



In [ ]:
np.random.rand(2,2)

array([[0.5358106 , 0.26230633],
       [0.03744868, 0.05081619]])

In [ ]:
np.random.randn(2,2)

array([[ 1.90489138, -0.54691474],
       [ 0.61636764,  0.115744  ]])

In [ ]:
mean_value = np.mean(arr)


In [ ]:
data = {'name': ['Alice', 'Bob', 'Charlie'], 'age': [25, 30, 35]}
df = pd.DataFrame(data)


In [ ]:
data = {'name': ['Alice', 'Bob', 'Charlie'], 'age': [25, 30, 35]}
df = pd.DataFrame(data)
df

name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df.head()


name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df.tail()


name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df.shape


(3, 2)

In [ ]:
df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   name    3 non-null      object
 1   age     3 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 180.0+ bytes


In [ ]:
df.describe()


age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [ ]:
df['name']


0      Alice
1        Bob
2    Charlie
Name: name, dtype: object

In [ ]:
df[['name', 'age']]


name  age
0    Alice   25
1      Bob   30
2  Charlie   35

In [ ]:
df.iloc[0]  # First row


name    Alice
age        25
Name: 0, dtype: object

In [ ]:
df[df['age'] > 30]


name  age
2  Charlie   35

In [ ]:
df.drop(columns=['age'], inplace=True)


In [ ]:
df.isnull().sum()


name    0
dtype: int64

In [ ]:
df1 = pd.DataFrame({'Name': ['Alice'], 'age': [25]})
df2 = pd.DataFrame({'Name': ['Bob'], 'age': [30]})
df_concat = pd.concat([df1, df2])
df_concat

Name  age
0  Alice   25
0    Bob   30